spring.application.name=finsight-ai
spring.flyway.clean-disabled=true
spring.flyway.clean-on-validation-error=false


# ----------------------------------------
# LOGGING CONFIGURATION
# ----------------------------------------
# Tell Spring Boot where to save the log file
logging.file.name=logs/finsight-error.log

# Tell it how big the file can get before it creates a new one (prevents crashing your hard drive)
logging.logback.rollingpolicy.max-file-size=10MB

# Keep the last 7 days of logs, then delete the old ones
logging.logback.rollingpolicy.max-history=7


# --- ACTUATOR HEALTH CHECKS ---
# Expose the health endpoint over HTTP
management.endpoints.web.exposure.include=health
# Show details (like database status) ONLY to authorized users, but show simple UP/DOWN publicly
management.endpoint.health.show-details=when_authorized
